# Generated by Django 3.2.4 on 2021-06-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topmanagers',
            old_name='Name',
            new_name='name',
        ),
    ]
