# Generated by Django 3.2.4 on 2021-06-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_topmanagers_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='link',
            new_name='facebook',
        ),
        migrations.AddField(
            model_name='links',
            name='inst',
            field=models.URLField(default='http:\\google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='links',
            name='off_site',
            field=models.URLField(default='http:\\google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='links',
            name='twitter',
            field=models.URLField(default='http:\\google.com'),
            preserve_default=False,
        ),
    ]
