# Generated by Django 3.2.4 on 2021-06-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_organization_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='inst',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='off_site',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
