# Generated by Django 3.2.4 on 2021-06-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_topmanagers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasofactivity',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
